# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stboite_display.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stboite_display.proto\x12\x12stboite.v1.display\"\xd4\x01\n\x10RenderingRequest\x12<\n\x04type\x18\x01 \x01(\x0e\x32..stboite.v1.display.RenderingRequest.PixelType\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"U\n\tPixelType\x12\x07\n\x03ONE\x10\x00\x12\x05\n\x01L\x10\x01\x12\x07\n\x03RGB\x10\x02\x12\x08\n\x04RGBA\x10\x03\x12\x08\n\x04\x43MYK\x10\x04\x12\t\n\x05YCBCR\x10\x05\x12\x07\n\x03LAB\x10\x06\x12\x07\n\x03HSV\x10\x07\"\xc8\x01\n\x11RenderingResponse\x12@\n\x06status\x18\x01 \x01(\x0e\x32\x30.stboite.v1.display.RenderingResponse.StatusCode\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\"`\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x1a\n\x16PIXEL_TYPE_NOT_ALLOWED\x10\x01\x12\x19\n\x15\x44IMENSION_NOT_ALLOWED\x10\x02\x12\x13\n\x0fINVALID_PAYLOAD\x10\x03\x32s\n\x10RenderingService\x12_\n\x10\x44isplayRendering\x12$.stboite.v1.display.RenderingRequest\x1a%.stboite.v1.display.RenderingResponseb\x06proto3')



_RENDERINGREQUEST = DESCRIPTOR.message_types_by_name['RenderingRequest']
_RENDERINGRESPONSE = DESCRIPTOR.message_types_by_name['RenderingResponse']
_RENDERINGREQUEST_PIXELTYPE = _RENDERINGREQUEST.enum_types_by_name['PixelType']
_RENDERINGRESPONSE_STATUSCODE = _RENDERINGRESPONSE.enum_types_by_name['StatusCode']
RenderingRequest = _reflection.GeneratedProtocolMessageType('RenderingRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENDERINGREQUEST,
  '__module__' : 'stboite_display_pb2'
  # @@protoc_insertion_point(class_scope:stboite.v1.display.RenderingRequest)
  })
_sym_db.RegisterMessage(RenderingRequest)

RenderingResponse = _reflection.GeneratedProtocolMessageType('RenderingResponse', (_message.Message,), {
  'DESCRIPTOR' : _RENDERINGRESPONSE,
  '__module__' : 'stboite_display_pb2'
  # @@protoc_insertion_point(class_scope:stboite.v1.display.RenderingResponse)
  })
_sym_db.RegisterMessage(RenderingResponse)

_RENDERINGSERVICE = DESCRIPTOR.services_by_name['RenderingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RENDERINGREQUEST._serialized_start=46
  _RENDERINGREQUEST._serialized_end=258
  _RENDERINGREQUEST_PIXELTYPE._serialized_start=173
  _RENDERINGREQUEST_PIXELTYPE._serialized_end=258
  _RENDERINGRESPONSE._serialized_start=261
  _RENDERINGRESPONSE._serialized_end=461
  _RENDERINGRESPONSE_STATUSCODE._serialized_start=365
  _RENDERINGRESPONSE_STATUSCODE._serialized_end=461
  _RENDERINGSERVICE._serialized_start=463
  _RENDERINGSERVICE._serialized_end=578
# @@protoc_insertion_point(module_scope)
