# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stboite_input.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stboite_input.proto\x12\x10stboite.v1.input\x1a\x1bgoogle/protobuf/empty.proto\"q\n\nTouchEvent\x12\x32\n\x06points\x18\x01 \x03(\x0b\x32\".stboite.v1.input.TouchEvent.Point\x1a/\n\x05Point\x12\t\n\x01X\x18\x01 \x01(\r\x12\t\n\x01Y\x18\x02 \x01(\r\x12\x10\n\x08Pressure\x18\x03 \x01(\r2]\n\x11TouchInputService\x12H\n\x10HandleTouchEvent\x12\x1c.stboite.v1.input.TouchEvent\x1a\x16.google.protobuf.Emptyb\x06proto3')



_TOUCHEVENT = DESCRIPTOR.message_types_by_name['TouchEvent']
_TOUCHEVENT_POINT = _TOUCHEVENT.nested_types_by_name['Point']
TouchEvent = _reflection.GeneratedProtocolMessageType('TouchEvent', (_message.Message,), {

  'Point' : _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
    'DESCRIPTOR' : _TOUCHEVENT_POINT,
    '__module__' : 'stboite_input_pb2'
    # @@protoc_insertion_point(class_scope:stboite.v1.input.TouchEvent.Point)
    })
  ,
  'DESCRIPTOR' : _TOUCHEVENT,
  '__module__' : 'stboite_input_pb2'
  # @@protoc_insertion_point(class_scope:stboite.v1.input.TouchEvent)
  })
_sym_db.RegisterMessage(TouchEvent)
_sym_db.RegisterMessage(TouchEvent.Point)

_TOUCHINPUTSERVICE = DESCRIPTOR.services_by_name['TouchInputService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOUCHEVENT._serialized_start=70
  _TOUCHEVENT._serialized_end=183
  _TOUCHEVENT_POINT._serialized_start=136
  _TOUCHEVENT_POINT._serialized_end=183
  _TOUCHINPUTSERVICE._serialized_start=185
  _TOUCHINPUTSERVICE._serialized_end=278
# @@protoc_insertion_point(module_scope)
