# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import stboite_display_pb2 as stboite__display__pb2


class RenderingServiceStub(object):
    """RenderingService provides an API to display an image on a specific device.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DisplayRendering = channel.unary_unary(
                '/stboite.v1.display.RenderingService/DisplayRendering',
                request_serializer=stboite__display__pb2.RenderingRequest.SerializeToString,
                response_deserializer=stboite__display__pb2.RenderingResponse.FromString,
                )


class RenderingServiceServicer(object):
    """RenderingService provides an API to display an image on a specific device.
    """

    def DisplayRendering(self, request, context):
        """DisplayRendering displays the encapsulated image on the device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenderingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DisplayRendering': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayRendering,
                    request_deserializer=stboite__display__pb2.RenderingRequest.FromString,
                    response_serializer=stboite__display__pb2.RenderingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stboite.v1.display.RenderingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RenderingService(object):
    """RenderingService provides an API to display an image on a specific device.
    """

    @staticmethod
    def DisplayRendering(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stboite.v1.display.RenderingService/DisplayRendering',
            stboite__display__pb2.RenderingRequest.SerializeToString,
            stboite__display__pb2.RenderingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
